# Standards: 0.1
---
- name: Download service binary
  get_url:
    url: "{{ ipv6nat_download }}"
    dest: /usr/bin/ipv6nat
    mode: 0774
  tags:
    - ipv6nat

- name: Write env config
  notify:
    - Restart ipv6nat
  template:
    src: default.j2
    dest: /etc/default/ipv6nat
  tags:
    - ipv6nat

- name: Write service file
  notify:
    - Restart ipv6nat
  template:
    src: service.j2
    dest: /etc/systemd/system/ipv6nat.service
  tags:
    - ipv6nat

- name: Start ipv6nat service
  systemd:
    name: ipv6nat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - ipv6nat

...
